export const GET_USERS_LIST_START = 'GET_USERS_LIST_START';
export const GET_USERS_LIST_FAIL = 'GET_USERS_LIST_FAIL';
export const GET_USERS_LIST_SUCCESS = 'GET_USERS_LIST_SUCCESS';

export const DELETE_USER_START = 'DELETE_USER_START';
export const DELETE_USER_FAIL = 'DELETE_USER_FAIL';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';

export const LOGIN_USER_START = 'LOGIN_USER_START';
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';

export const REGISTER_USER_START = 'REGISTER_USER_START';
export const REGISTER_USER_FAIL = 'REGISTER_USER_FAIL';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';

export const GET_ROLES_LIST_START = 'GET_ROLES_LIST_START';
export const GET_ROLES_LIST_FAIL = 'GET_ROLES_LIST_FAIL';
export const GET_ROLES_LIST_SUCCESS = 'GET_ROLES_LIST_SUCCESS';

export const GET_USERBYID_LIST_START = 'GET_USERBYID_LIST_START';
export const GET_USERBYID_LIST_FAIL = 'GET_USERBYID_LIST_FAIL';
export const GET_USERBYID_LIST_SUCCESS = 'GET_USERBYID_LIST_SUCCESS';

export const UPDATE_USER_START = 'UPDATE_USER_START';
export const UPDATE_USER_FAIL = 'UPDATE_USER_FAIL';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';

export const GET_PRODUCTS_LIST_START = 'GET_PRODUCTS_LIST_START';
export const GET_PRODUCTS_LIST_FAIL = 'GET_PRODUCTS_LIST_FAIL';
export const GET_PRODUCTS_LIST_SUCCESS = 'GET_PRODUCTS_LIST_SUCCESS';

export const DELETE_PRODUCT_START = 'DELETE_PRODUCT_START';
export const DELETE_PRODUCT_FAIL = 'DELETE_PRODUCT_FAIL';
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS';

export const INSERT_PRODUCT_START = 'INSERT_PRODUCT_START';
export const INSERT_PRODUCT_FAIL = 'INSERT_PRODUCT_FAIL';
export const INSERT_PRODUCT_SUCCESS = 'INSERT_PRODUCT_SUCCESS';

export const UPDATE_PRODUCT_START = 'UPDATE_PRODUCT_START';
export const UPDATE_PRODUCT_FAIL = 'UPDATE_PRODUCT_FAIL';
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS';

export const UPDATE_BUNDLE_START = 'UPDATE_BUNDLE_START';
export const UPDATE_BUNDLE_FAIL = 'UPDATE_BUNDLE_FAIL';
export const UPDATE_BUNDLE_SUCCESS = 'UPDATE_BUNDLE_SUCCESS';

export const GET_PRODUCTBYID_LIST_START = 'GET_PRODUCTBYID_LIST_START';
export const GET_PRODUCTBYID_LIST_FAIL = 'GET_PRODUCTBYID_LIST_FAIL';
export const GET_PRODUCTBYID_LIST_SUCCESS = 'GET_PRODUCTBYID_LIST_SUCCESS';

export const GET_BUNDLES_LIST_START = 'GET_BUNDLES_LIST_START';
export const GET_BUNDLES_LIST_FAIL = 'GET_BUNDLES_LIST_FAIL';
export const GET_BUNDLES_LIST_SUCCESS = 'GET_BUNDLES_LIST_SUCCESS';

export const DELETE_BUNDLE_START = 'DELETE_BUNDLE_START';
export const DELETE_BUNDLE_FAIL = 'DELETE_BUNDLE_FAIL';
export const DELETE_BUNDLE_SUCCESS = 'DELETE_BUNDLE_SUCCESS';

export const INSERT_BUNDLE_START = 'INSERT_BUNDLE_START';
export const INSERT_BUNDLE_FAIL = 'INSERT_BUNDLE_FAIL';
export const INSERT_BUNDLE_SUCCESS = 'INSERT_BUNDLE_SUCCESS';

export const GET_BUNDLE_PRODUCT_LIST_START = 'GET_BUNDLE_PRODUCT_LIST_START';
export const GET_BUNDLE_PRODUCT_LIST_FAIL = 'GET_BUNDLE_PRODUCT_LIST_FAIL';
export const GET_BUNDLE_PRODUCT_LIST_SUCCESS = 'GET_BUNDLE_PRODUCT_LIST_SUCCESS';

export const DELETE_BUNDLE_PRODUCT_START = 'DELETE_BUNDLE_PRODUCT_START';
export const DELETE_BUNDLE_PRODUCT_FAIL = 'DELETE_BUNDLE_PRODUCT_FAIL';
export const DELETE_BUNDLE_PRODUCT_SUCCESS = 'DELETE_BUNDLE_PRODUCT_SUCCESS';

export const INSERT_BUNDLE_PRODUCT_START = 'INSERT_BUNDLE_PRODUCT_START';
export const INSERT_BUNDLE_PRODUCT_FAIL = 'INSERT_BUNDLE_PRODUCT_FAIL';
export const INSERT_BUNDLE_PRODUCT_SUCCESS = 'INSERT_BUNDLE_PRODUCT_SUCCESS';

export const SELECT_USER = 'SELECT_USER';
export const SELECT_PRODUCT = 'SELECT_PRODUCT';
export const SELECT_BUNDLE = 'SELECT_BUNDLE';

export const LOGOUT_USER = 'LOGOUT_USER';
