export const GET_USERS_LIST_START = 'GET_USERS_LIST_START';
export const GET_USERS_LIST_FAIL = 'GET_USERS_LIST_FAIL';
export const GET_USERS_LIST_SUCCESS = 'GET_USERS_LIST_SUCCESS';

export const DELETE_USER_START = 'DELETE_USER_START';
export const DELETE_USER_FAIL = 'DELETE_USER_FAIL';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';

export const LOGIN_USER_START = 'LOGIN_USER_START';
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';

export const REGISTER_USER_START = 'REGISTER_USER_START';
export const REGISTER_USER_FAIL = 'REGISTER_USER_FAIL';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';

export const LOGOUT_USER = 'LOGOUT_USER';
